var gallery = [];
var galleryname = "journal";
var sugar = null;


var defaultGallery=
["wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"oyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyoyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyoyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyoyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyoyoyoyoyyoyoyoyooyoyoyoyyoyoyoyooyoyoyoyyoyoyoyo",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"yyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykkkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkyyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykkkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkyyyyyykkykkkkkyykyyyyykkykkkkkyykyyyyykkykkkkkyyk",
"bbbbbbbbbbbbbbbbbbbbbbbbyyybbbybbyyybbbybbbbbbbbbbbbbbnbbbbbbbbnbbbbbbbbyybybybbybyyybbbbbbbbbbbnnnnbnnnnnnnnbnnbbbbbbonbbbbbbnobbbbbbbnoooobboonnnnnnngnnnnnngnnnnnnnggnnnnnnngnnnnnnnnnnnnnngngggggggggggggggggggggggggggggggggggggggggggggggg",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"bbgggbrrggbbbgyybbgggbrrggbbbgyybbgggbrrggbbbgyyryyrrryyyrryyyrrryyrrryyyrryyyrrryyrrryyyrryyyrrggbbyygbbbggrrbgggbbyygbbbggrrbgggbbyygbbbggrrbgbbgggbrrggbbbgyybbgggbrrggbbbgyybbgggbrrggbbbgyyrvvrrrvvyooyyyoorvvrrrvvyvvyyyvvroorrrooyvvyyyvv",
"vvvvvvbvbbbbvbbbbbbbbbybbyybbbyybyybbbyybyybbbyybbbvvbybywyybyryywwyyywrwwwwwwwwwwwwwwowwwwwwywoyybbbywbwwrwwrrwwwwwrwrrwwwwwwowwwowwoowwowwowwowggybwggwggwwrrgwggwrwgrwggwwwggwogwwoggwgowowgggnngggnnnnnngnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnngnn",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"];


function loadGallery(loaded){
	if (loaded != null) gallery = loaded.split('#');
	else {
		gallery = defaultGallery;
	}
}

function saveGallery(){
	sugar.sendMessage("save-gallery", gallery.join('#'));
}

